export const mambaConfig = {
  url: 'https://www.mamba.ru/auth',
  selectors: {
    emailInput: 'input[name="login"]',
    passwordInput: 'input[name="password"]',
    loginButton: 'button[type="submit"]',
    successIndicator: null,
    captchaElements: [
      {
        tag: 'HTML',
        className: '',
        id: '',
        type: 'recaptcha'
      },
      {
        tag: 'BODY',
        className: '',
        id: '',
        type: 'recaptcha'
      },
      {
        tag: 'SCRIPT',
        className: '',
        id: '',
        type: 'recaptcha'
      }
    ],
    twoFAElements: []
  },
  cookies: [
    'mb_track_id',
    'mb_track_source_id',
    'mb_source_info',
    's_post',
    'rerf',
    'ipp_uid',
    'st_uid',
    'af_id',
    'afUserId',
    'serv',
    'AF_SYNC',
    'bh',
    '_ym_uid',
    '_ym_d',
    '_ym_isad',
    'sync_cookie_csrf',
    'cid',
    'adrdel',
    'adrcid',
    'acs_3',
    'yabs-sid',
    'i',
    'yandexuid',
    'yuidss',
    'ymex',
    'receive-cookie-deprecation',
    'sync_cookie_csrf_secondary',
    'sync_cookie_ok_secondary',
    'mmbTracker',
    'mmbTrackerTarget',
    'LOGIN',
    'start_with_auth_form',
    'mmbUID',
    'UID',
    'mmbSECRET',
    'SECRET',
    'LEVEL',
    'registered_once',
    'mmbsid',
    'unauth_lang'
  ],
  antiBot: {
    captchaDetected: true,
    captchaType: 'recaptcha',
    twoFADetected: false,
    recommendations: [
      'IMPORTANT: reCAPTCHA detected on login form - may require manual solving or 2Captcha service',
      'Use realistic delays between actions (500-2000ms)',
      'Use headless: true with stealth plugin for production',
      'Maintain consistent user-agent across requests',
      'Handle cookies and sessions properly',
      'Use viewport and screen size similar to real browsers (1280x720+)',
      'Add randomized delays between interactions',
      'Respect rate limiting - avoid rapid-fire requests',
      'For automated testing: Consider using browser context with persistent storage',
      'Monitor the page.url() for redirect after login submission'
    ]
  },
  timestamp: '2025-12-05T11:28:11.066Z'
};

export const mambaSelectors = {
  emailInput: 'input[name="login"]',
  passwordInput: 'input[name="password"]',
  loginButton: 'button[type="submit"]',
  successIndicator: null,
} as const;

export const mambaCookies = [
  'mb_track_id',
  'mb_track_source_id',
  'mb_source_info',
  's_post',
  'rerf',
  'ipp_uid',
  'st_uid',
  'af_id',
  'afUserId',
  'serv',
  'AF_SYNC',
  'bh',
  '_ym_uid',
  '_ym_d',
  '_ym_isad',
  'sync_cookie_csrf',
  'cid',
  'adrdel',
  'adrcid',
  'acs_3',
  'yabs-sid',
  'i',
  'yandexuid',
  'yuidss',
  'ymex',
  'receive-cookie-deprecation',
  'sync_cookie_csrf_secondary',
  'sync_cookie_ok_secondary',
  'mmbTracker',
  'mmbTrackerTarget',
  'LOGIN',
  'start_with_auth_form',
  'mmbUID',
  'UID',
  'mmbSECRET',
  'SECRET',
  'LEVEL',
  'registered_once',
  'mmbsid',
  'unauth_lang'
] as const;

export const mambaSessionService = {
  url: 'https://www.mamba.ru/auth',
  selectors: {
    emailInput: 'input[name="login"]',
    passwordInput: 'input[name="password"]',
    loginButton: 'button[type="submit"]',
    successIndicator: null,
  },
  cookieNames: [
    'mb_track_id',
    'mb_track_source_id',
    'mb_source_info',
    's_post',
    'rerf',
    'ipp_uid',
    'st_uid',
    'af_id',
    'afUserId',
    'serv',
    'AF_SYNC',
    'bh',
    '_ym_uid',
    '_ym_d',
    '_ym_isad',
    'sync_cookie_csrf',
    'cid',
    'adrdel',
    'adrcid',
    'acs_3',
    'yabs-sid',
    'i',
    'yandexuid',
    'yuidss',
    'ymex',
    'receive-cookie-deprecation',
    'sync_cookie_csrf_secondary',
    'sync_cookie_ok_secondary',
    'mmbTracker',
    'mmbTrackerTarget',
    'LOGIN',
    'start_with_auth_form',
    'mmbUID',
    'UID',
    'mmbSECRET',
    'SECRET',
    'LEVEL',
    'registered_once',
    'mmbsid',
    'unauth_lang'
  ],
  antiBot: {
    captchaDetected: true,
    captchaType: 'recaptcha',
    twoFADetected: false,
    recommendations: [
      'IMPORTANT: reCAPTCHA detected on login form - may require manual solving or 2Captcha service',
      'Use realistic delays between actions (500-2000ms)',
      'Use headless: true with stealth plugin for production',
      'Maintain consistent user-agent across requests',
      'Handle cookies and sessions properly',
      'Use viewport and screen size similar to real browsers (1280x720+)',
      'Add randomized delays between interactions',
      'Respect rate limiting - avoid rapid-fire requests',
      'For automated testing: Consider using browser context with persistent storage',
      'Monitor the page.url() for redirect after login submission'
    ]
  }
};
